### ISSUE TITLE
Define Project Architecture

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/aide_gui#1]
It would be nice to have a descriptive diagram, much like the overall AIDE diagram, that describes the various components of the GUI. 

These are my initial thoughts on the implementation of the GUI:
- The GUI should be able to inspect what designs aide_draw can draw, and which aide_design can design and auto-generate the relative GUI buttons.
- The overall flow of the AIDE plugin's GUI should be intuitive and simple. There are three distinct tasks that the GUI aids in:
    * initiating designing of the plant. 
    * start drawing the plant from either the designed JSON or another one someone sent
    * start documenting the plant (choose a template/type of document, and send request off to aide_document.
- In one sense, the GUI does the same thing over and over again. It creates a button, prompts and collects data from the user, calls the relevant function with said data, and returns the result. The more abstractly you can define these tasks, the less replication you will have. 

The architecture drawing should propose large-level components of the GUI package. Think of it as the GUI- zoomed in part of the overall AIDE design diagram. It should answer the following equations:
- What major sub-packages are needed? What are the vague boundaries and responsibilities of those sub-modules?
- How will the sub modules generate the user experience?
- How does data flow throughout the system?
- How does the GUI call external AIDE packages?

I would love to work on this with y'all. I recommend starting a google drawing and sharing me. I can make comments and suggestions.

**Comment by ach238** [comment]
Hey Ethan! We made a google drawing and shared that with you if you wanna take a look and give us some suggestions

**Comment by ethan92429** [comment]
@ach238 Where is it? I just need the file name if you don't want to link it!

**Comment by ach238** [comment]
here's the link: https://docs.google.com/a/cornell.edu/drawings/d/1Wx0-HbvOSo6qYDUNG_nqSEbtwN5-B-4QEhm20BV67jw/edit?usp=sharing

**Comment by ethan92429** [comment]
This looks like a good start. You'll want to expound on these tasks. What module is responsible for creating the buttons? What does it need to know, and what should it return? 

Think about the interfaces between each major function. ie, the parameters called and what it will return. There are two types of interfaces to consider. Those outside your package and those within. External or outside interfaces are the functions your allowing draw, document, etc. to use from you and all the functions you are hoping to use of theirs. I currently see no reason you need to expose any functions for others to use, but it is possible. The internal interfaces only require conversation within your team to develop. Once you develop them well, you can all work on separate components without getting in one another's way.
