### ISSUE TITLE
Single Design vs. Whole Plant

### ISSUE THREAD

**Issue by ach238** [AguaClara/aide_gui#10]
- Single design vs. design of a whole plant, need all those tabs/ inputs?
- What happens when you use the same parameter for a single design as the whole plant?
- Second GUI to track what the user actually wants to make, select a JSON (one possibility)

**Comment by ethan92429** [comment]
@ach238. 

1. One thing to keep in mind is that the GUI is a designed experience for users, and therefore should be used sparingly. For instance, I think it makes sense to use it to build a GUI for the whole plant build, but I'm reluctant to make it available for every little part. To draw those, the users will modify the controlling YAML manually. 
2. I'm not sure what you mean here, please describe!
3. There has to be one GUI that allows the user to point to a GUI or set of GUIs in general. This will be simply a textedit box that lets them paste in a URL that points to the GUI YAML. Well, I suppose we'll discuss this all later today!
