### ISSUE TITLE
Next Steps?

### ISSUE THREAD

**Issue by ashleyhe16** [AguaClara/aide_gui#19]
@ethan92429 we believe we have a minimum viable product mostly completed if not completed (please see test_gui), what are the next steps we should take?

@eldorbekpulatov @Anishka99

**Comment by ethan92429** [comment]
@AguaClara/aide_gui There are many things you could do now in terms of new features, but I think before we focus on new things, let's make sure the MVP is incorporating coding best practices. You need to fully comment your code... meaning [use numpy style docstrings](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) for all functions, modules and classes. You need to make sure the code is fully tested... this can get complex - start a new issue for this and we can discuss options. Once you are satisfied that it is production worthy, you should commit it to the master branch of aide_gui. Next, make sure that your gui plugin is available at the [autodesk store as AIDE](https://apps.autodesk.com/FUSION/en/Home/Index) To do this properly, you need to document how to put it up on the store and how to update it in the future. Make an issue for all these tasks and message me if you get lost/need more guidance.
